### ISSUE TITLE
Intel run@cnaf doesn't work

### ISSUE THREAD

**Issue by titoiride** [ALaDyn/ALaDyn#42]
Compiling and running with INTEL@cnaf doesn't work.

The `epic.txt` is

`hpc-200-06-22.cr.cnaf.infn.it.25191Driver initialization failure on /dev/ipath (err=23)
[128] MPI startup(): tmi fabric is not available and fallback fabric is not enabled`,

the `opic.txt` is

`hpc-200-06-22.cr.cnaf.infn.it.25191ipath_userinit: assign_context command failed: Invalid argument`.

Gnu compiler GCC works fine

**Comment by cenit** [comment]
there are some problematic nodes in the hpc@cnaf cluster, that have /dev/ipath driver broken. It's *not* a problem in the code itself, so for now I'd just close it. Just keep insisting and when you find a working combination of nodes just use it. On Monday I will let the cluster administrators know about the problem. Otherwise just use the OpenMPI version, which as you already found out works anyway (even if a little bit slower than the IntelMPI one)
